project:
  type: website
  output-dir: docs

website:
  title: "Muslim Diversity Study"
  
  page-footer:
    left: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
    right: |
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://usman-afzali.github.io/muslim-diversity/)</span>
    background: "#d85e33"
  
  navbar:
    pinned: true
    left:
      - text: "Overview"
        file: pages/overview.qmd
      - text: "Vision Statement"
        file: pages/vision.qmd
      - text: "Team"
        file: pages/team.qmd
      - text: "Participant Confidentiality"
        file: pages/confid.qmd
      - text: "Reports and Publications"
        file: pages/reports.qmd
      - text: "Ethics Approval"
        file: pages/ethics.qmd  
    right:
      - icon: github
        href: https://github.com/usman-afzali/muslim-diversity
    page-navigation: true

format:
  html:
    theme: [united, styles.scss]
    css: styles.scss
    highlight-style: tango

editor: source

